import type { Briefing } from './types'

export function buildMarkdown(briefing: Briefing): string {
  const lines: string[] = [
    `# ${briefing.title}`,
    '',
    `> Generated by [LinkLoom](https://github.com/maloqab/linkloom) on ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`,
    '',
  ]

  if (briefing.sources.length > 0) {
    lines.push('## Sources', '')
    const valid = briefing.sources.filter(s => s.isValid)
    const invalid = briefing.sources.filter(s => !s.isValid)

    for (const s of valid) {
      const label = s.title !== s.domain ? `${s.title} (${s.domain})` : s.domain
      lines.push(`- [${label}](${s.url})`)
    }

    if (invalid.length > 0) {
      lines.push('', '### Unresolved')
      for (const s of invalid) lines.push(`- ${s.url}`)
    }
    lines.push('')
  }

  if (briefing.notes.length > 0) {
    lines.push('## Notes', '')
    for (const n of briefing.notes) lines.push(`- ${n.text}`)
    lines.push('')
  }

  if (briefing.sources.length === 0 && briefing.notes.length === 0) {
    lines.push('*Empty briefing.*', '')
  }

  return lines.join('\n')
}

export function briefingToFilename(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') || 'linkloom-brief'
  ) + '.md'
}
