import { useEffect, useMemo, useState } from 'react'
import './App.css'

type UrlItem = {
  id: string
  raw: string
  isValid: boolean
  normalized?: string
}

type NoteItem = {
  id: string
  text: string
}

type BriefState = {
  urlsRaw: string
  notesRaw: string
}

const STORAGE_KEY = 'linkloom:v1'

function parseUrls(urlsRaw: string): UrlItem[] {
  return urlsRaw
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((raw, index) => {
      try {
        const normalized = new URL(raw).toString()
        return { id: `url-${index + 1}`, raw, isValid: true, normalized }
      } catch {
        return { id: `url-${index + 1}`, raw, isValid: false }
      }
    })
}

function parseNotes(notesRaw: string): NoteItem[] {
  return notesRaw
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((text, index) => ({ id: `note-${index + 1}`, text }))
}

function normalizeTitle(urlItems: UrlItem[], noteItems: NoteItem[]): string {
  const firstValid = urlItems.find((item) => item.isValid && item.normalized)
  if (firstValid?.normalized) {
    const host = new URL(firstValid.normalized).hostname.replace(/^www\./, '')
    return `Briefing • ${host}`
  }

  if (noteItems.length > 0) return 'LinkLoom Notes Brief'
  return 'Untitled Brief'
}

function buildMarkdown(title: string, urlItems: UrlItem[], noteItems: NoteItem[]): string {
  const now = new Date().toISOString()
  const validUrls = urlItems.filter((item) => item.isValid)
  const invalidUrls = urlItems.filter((item) => !item.isValid)

  const sections = [
    `# ${title}`,
    '',
    `> Generated by LinkLoom on ${now}`,
    '',
    '## Sources',
    ...(validUrls.length
      ? validUrls.map((item) => `- [${item.raw}](${item.normalized})`)
      : ['- _No valid URLs added_']),
    ...(invalidUrls.length
      ? ['', '### Invalid URLs (review needed)', ...invalidUrls.map((item) => `- ${item.raw}`)]
      : []),
    '',
    '## Notes',
    ...(noteItems.length ? noteItems.map((item) => `- ${item.text}`) : ['- _No notes added_']),
    '',
  ]

  return sections.join('\n')
}

function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  document.body.appendChild(anchor)
  anchor.click()
  document.body.removeChild(anchor)
  URL.revokeObjectURL(url)
}

function loadInitialState(): BriefState {
  const fallback: BriefState = { urlsRaw: '', notesRaw: '' }

  try {
    const stored = localStorage.getItem(STORAGE_KEY)
    if (!stored) return fallback
    const parsed = JSON.parse(stored) as BriefState
    return {
      urlsRaw: parsed.urlsRaw ?? '',
      notesRaw: parsed.notesRaw ?? '',
    }
  } catch {
    localStorage.removeItem(STORAGE_KEY)
    return fallback
  }
}

function App() {
  const initialState = useMemo(() => loadInitialState(), [])
  const [urlsRaw, setUrlsRaw] = useState(initialState.urlsRaw)
  const [notesRaw, setNotesRaw] = useState(initialState.notesRaw)
  const [notice, setNotice] = useState('')

  useEffect(() => {
    const nextState: BriefState = { urlsRaw, notesRaw }
    localStorage.setItem(STORAGE_KEY, JSON.stringify(nextState))
  }, [notesRaw, urlsRaw])

  const urlItems = useMemo(() => parseUrls(urlsRaw), [urlsRaw])
  const noteItems = useMemo(() => parseNotes(notesRaw), [notesRaw])
  const title = useMemo(() => normalizeTitle(urlItems, noteItems), [noteItems, urlItems])
  const markdown = useMemo(() => buildMarkdown(title, urlItems, noteItems), [noteItems, title, urlItems])

  const invalidCount = urlItems.filter((item) => !item.isValid).length
  const hasContent = urlItems.length > 0 || noteItems.length > 0

  const handleExport = () => {
    if (!hasContent) {
      setNotice('Add at least one URL or note before exporting.')
      return
    }

    const fileBase = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')

    downloadMarkdown(`${fileBase || 'linkloom-brief'}.md`, markdown)
    setNotice('Markdown exported successfully.')
  }

  const handleClear = () => {
    setUrlsRaw('')
    setNotesRaw('')
    setNotice('Inputs cleared. Local draft reset.')
    localStorage.removeItem(STORAGE_KEY)
  }

  return (
    <main className="app-shell">
      <header className="hero">
        <h1>LinkLoom</h1>
        <p>Turn scattered links and notes into one clean briefing page.</p>
      </header>

      {notice ? <p className="notice">{notice}</p> : null}

      <section className="layout-grid">
        <section className="panel panel-input">
          <h2>Input</h2>

          <label>
            URLs (one per line)
            <textarea
              value={urlsRaw}
              onChange={(event) => {
                setUrlsRaw(event.target.value)
                setNotice('')
              }}
              placeholder="https://example.com/article\nhttps://news.site/story"
              rows={8}
            />
          </label>

          {invalidCount > 0 ? <p className="warning">{invalidCount} URL(s) look invalid and will be flagged in export.</p> : null}

          <label>
            Notes
            <textarea
              value={notesRaw}
              onChange={(event) => {
                setNotesRaw(event.target.value)
                setNotice('')
              }}
              placeholder="Paste raw notes, bullets, fragments..."
              rows={8}
            />
          </label>

          <div className="actions">
            <button type="button" className="ghost" onClick={handleClear}>
              Clear
            </button>
            <button type="button" onClick={handleExport} disabled={!hasContent}>
              Export Markdown
            </button>
          </div>
        </section>

        <article className="panel panel-brief">
          <div className="brief-header">
            <h2>{title}</h2>
            <span>{urlItems.length} source(s) • {noteItems.length} note line(s)</span>
          </div>

          <section>
            <h3>Sources</h3>
            {urlItems.length ? (
              <ul>
                {urlItems.map((item) => (
                  <li key={item.id} className={item.isValid ? '' : 'invalid'}>
                    {item.isValid && item.normalized ? (
                      <a href={item.normalized} target="_blank" rel="noreferrer">
                        {item.raw}
                      </a>
                    ) : (
                      item.raw
                    )}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="empty">No URLs yet.</p>
            )}
          </section>

          <section>
            <h3>Notes</h3>
            {noteItems.length ? (
              <ul>
                {noteItems.map((item) => (
                  <li key={item.id}>{item.text}</li>
                ))}
              </ul>
            ) : (
              <p className="empty">No notes yet.</p>
            )}
          </section>
        </article>
      </section>
    </main>
  )
}

export default App
